(setq si-args
      '(
	("cyc-tms-reconsider-sentence" ("possibly-sentence-p" "&optional" "hlmt-p"))
	("cyc-rewrite" ("fort-p" "fort-p"))
	("cyc-remove-argument" ("possibly-sentence-p" "list-of-cycl-support-p" "&optional" "hlmt-p"))
	("cyc-remove-all-arguments" ("possibly-sentence-p" "&optional" "hlmt-p"))
	("cyc-add-argument" ("possibly-sentence-p" "list-of-cycl-support-p" "&optional" "hlmt-p" "assert-properties-p" "booleanp"))
	("cyc-continue-query" ("&optional" "query-id-p" "query-properties-p"))
	("cyc-query" ("possibly-sentence-p" "&optional" "hlmt-p" "query-properties-p"))
	("cyc-edit" ("possibly-sentence-p" "possibly-sentence-p" "&optional" "hlmt-p" "hlmt-p" "query-properties-p"))
	("cyc-unassert" ("possibly-sentence-p" "&optional" "hlmt-p"))
	("cyc-assert" ("possibly-sentence-p" "&optional" "hlmt-p" "assert-properties-p"))
	("cyc-merge" ("fort-p" "fort-p"))
	("cyc-rename" ("constant-p" "valid-constant-name"))
	("cyc-recreate" ("constant-p"))
	("cyc-kill" ("fort-p"))
	("cyc-create-new-permanent" ("new-constant-name-spec-p"))
	("cyc-create-new-ephemeral" ("new-constant-name-spec-p"))
	("cyc-create" ("new-constant-name-spec-p" "constant-external-id-p"))
	("cyc-find-or-create" ("valid-constant-name" "constant-external-id-p"))
	("fi-get-warning" ())
        ("fi-get-error" ())
        ("fi-prove" ("<formula>" "hlmt-p" "&optional" "<backchain>" "<number>" "<time>" "<depth>"))
        ("fi-hypothesize" ("<formula>" "hlmt-p" "&optional" "<name-prefix>" "<term-ids>"))
        ("fi-tms-reconsider-term" ("<term>" "&optional" "hlmt-p"))
        ("fi-tms-reconsider-gafs" ("<term>" "&optional" "<arg>" "<predicate>" "hlmt-p"))
        ("fi-tms-reconsider-mt" ("hlmt-p"))
        ("fi-tms-reconsider-formula" ("<formula>" "hlmt-p"))
        ("fi-ask-status" ())
        ("fi-continue-last-ask" ("&optional" "<backchain>" "<number>" "<time>" "<depth>" "<reconsider-deep>"))
        ("fi-ask" ("<formula>" "&optional" "hlmt-p" "<backchain>" "<number>" "<time>" "<depth>"))
        ("fi-blast" ("<formula>" "hlmt-p"))
        ("fi-edit" ("<old-formula>" "<new-formula>" "&optional" "hlmt-p" "hlmt-p" "<strength>" "<direction>"))
        ("fi-unassert" ("<formula>" "hlmt-p"))
        ("fi-assert" ("<formula>" "hlmt-p" "&optional" "<strength>" "<direction>"))
        ("fi-lookup" ("<formula>" "hlmt-p"))
        ("fi-rename" ("constant-p" "valid-constant-name"))
        ("fi-kill" ("fort-p"))
        ("fi-find-or-create" ("valid-constant-name" "&optional" "constant-external-id-p"))
        ("fi-create" ("valid-constant-name" "&optional" "constant-external-id-p"))
        ("fi-complete" ("<prefix>" "&optional" "<case-sensitive?>"))
        ("fi-find" ("valid-constant-name"))
        ("all-spec-attributes-if" ("function-spec-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-spec-attributes" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("min-argn-genl-attribute" ("<relation>" "integerp" "&optional" "hlmt-p"))
        ("argn-genl-attribute-of" ("<collection>" "integerp" "&optional" "hlmt-p"))
        ("argn-genl-attribute" ("<relation>" "integerp" "&optional" "hlmt-p"))
        ("all-genl-attributes-wrt" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-genl-attributes-if" ("function-spec-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-genl-attributes" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("gt-why-superior?" ("fort-p" "fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-why-completes-cycle?" ("fort-p" "fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-superiors" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-roots" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-redundant-superiors" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-redundant-inferiors" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-min-superiors-excluding" ("fort-p" "fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-min-superiors" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-min-nodes" ("fort-p" "listp" "&optional" "hlmt-p"))
        ("gt-min-ceilings" ("fort-p" "listp" "&optional" "<candidates>" "hlmt-p"))
        ("gt-max-nodes" ("fort-p" "listp" "&optional" "hlmt-p" "<direction>"))
        ("gt-max-inferiors-excluding" ("fort-p" "fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-max-inferiors" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-max-floors" ("fort-p" "listp" "&optional" "<candidates>" "hlmt-p"))
        ("gt-leaves" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-inferiors" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-has-superior?" ("fort-p" "fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-has-inferior?" ("fort-p" "fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-cycles?" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-compose-fn-all-superiors" ("fort-p" "fort-p" "function-spec-p" "&optional" "<combine-fn>" "hlmt-p"))
        ("gt-compose-fn-all-inferiors" ("fort-p" "fort-p" "function-spec-p" "&optional" "<combine-fn>" "hlmt-p"))
        ("gt-completes-cycle?" ("fort-p" "fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-co-superiors" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-co-inferiors" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-any-superior-path" ("fort-p" "fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-all-superiors" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-all-inferiors" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-all-dependent-inferiors" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("gt-all-accessible" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("union-all-spec-predicates" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("union-all-spec-inverses" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("union-all-genl-predicates" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("union-all-genl-inverses" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("spec-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("spec-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("some-all-genl-inverses" ("fort-p" "function-spec-p" "&optional" "hlmt-p" "<tv>"))
        ("not-spec-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("not-spec-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("not-genl-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("not-genl-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("genl-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("genl-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-genl-preds-among" ("el-fort-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("some-all-spec-preds" ("fort-p" "function-spec-p" "&optional" "hlmt-p" "<tv>"))
        ("map-all-spec-preds" ("fort-p" "function-spec-p" "&optional" "hlmt-p" "<tv>"))
        ("some-all-genl-preds" ("fort-p" "function-spec-p" "&optional" "hlmt-p" "<tv>"))
        ("map-all-genl-preds" ("fort-p" "function-spec-p" "&optional" "hlmt-p" "<tv>"))
        ("max-floor-mts-of-genl-inverse-paths" ("fort-p" "fort-p" "&optional" "<tv>"))
        ("max-floor-mts-of-genl-predicate-paths" ("fort-p" "fort-p" "&optional" "<tv>"))
        ("max-floor-predicates" ("listp" "&optional" "listp" "hlmt-p" "<tv>"))
        ("min-ceiling-predicates" ("listp" "&optional" "listp" "hlmt-p" "<tv>"))
        ("max-predicates" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("min-predicates" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("why-not-genl-inverse?" ("fort-p" "fort-p" "&optional" "hlmt-p" "<tv>" "<behavior>"))
        ("why-genl-inverse?" ("fort-p" "fort-p" "&optional" "hlmt-p" "<tv>" "<behavior>"))
        ("why-not-genl-predicate?" ("fort-p" "fort-p" "&optional" "hlmt-p" "<tv>" "<behavior>"))
        ("why-genl-predicate?" ("fort-p" "fort-p" "&optional" "hlmt-p" "<tv>" "<behavior>"))
        ("intersecting-predicates?" ("fort-p" "fort-p" "&optional" "hlmt-p"))
        ("any-not-genl-predicate?" ("fort-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("not-genl-inverse?" ("fort-p" "fort-p" "&optional" "hlmt-p" "<tv>"))
        ("not-genl-predicate?" ("fort-p" "fort-p" "&optional" "hlmt-p" "<tv>"))
        ("any-genl-predicate?" ("fort-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("spec-inverse?" ("fort-p" "fort-p" "&optional" "hlmt-p" "<tv>"))
        ("genl-inverse?" ("fort-p" "fort-p" "&optional" "hlmt-p" "<tv>"))
        ("genl-predicate?" ("fort-p" "fort-p" "&optional" "hlmt-p" "<tv>"))
        ("spec-predicate?" ("fort-p" "fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-not-spec-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-not-spec-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-spec-preds-wrt-arg" ("fort-p" "fort-p" "integerp" "&optional" "hlmt-p" "<tv>"))
        ("all-spec-preds-wrt-type" ("fort-p" "fort-p" "integerp" "&optional" "hlmt-p" "<tv>"))
        ("all-spec-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-spec-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-not-genl-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-not-genl-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-genl-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-genl-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("spec-inverse-siblings" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("spec-predicate-siblings" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("genl-inverse-siblings" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("genl-predicate-siblings" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("min-not-spec-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("min-not-spec-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("max-spec-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("max-spec-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("max-not-genl-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("max-not-genl-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("min-genl-inverses" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("min-genl-predicates" ("fort-p" "&optional" "hlmt-p" "<tv>"))
        ("why-not-genl?" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p" "<tv>" "<behavior>"))
        ("why-genl?" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p" "<tv>" "<behavior>"))
        ("spec-siblings" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-specs-among" ("el-fort-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("all-spec-any?" ("listp" "listp" "&optional" "hlmt-p" "<tv>"))
        ("all-not-specs" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-not-spec?" ("el-fort-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("all-genls-among" ("el-fort-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("any-all-specs" ("function-spec-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("map-all-specs" ("function-spec-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("any-all-genls" ("function-spec-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("map-all-genls" ("function-spec-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("why-not-assert-genls?" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p"))
        ("max-floor-mts-of-genls-paths" ("el-fort-p" "el-fort-p" "&optional" "<tv>"))
        ("shallower-col" ("el-fort-p" "el-fort-p"))
        ("lighter-col" ("el-fort-p" "el-fort-p"))
        ("any-genl-isa" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("why-collections-disjoint?" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p"))
        ("any-disjoint-collection-pair?" ("listp" "&optional" "hlmt-p"))
        ("any-disjoint-collection-pair" ("listp" "&optional" "hlmt-p"))
        ("max-floor-cols" ("listp" "&optional" "listp" "hlmt-p" "<tv>"))
        ("min-ceiling-cols" ("listp" "&optional" "listp" "hlmt-p" "<tv>"))
        ("max-cols" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("min-cols" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("collection-leaves" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("any-not-genl?" ("el-fort-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("not-genl?" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("any-genl-all?" ("listp" "listp" "&optional" "hlmt-p" "<tv>"))
        ("any-genl-any?" ("listp" "listp" "&optional" "hlmt-p" "<tv>"))
        ("all-spec?" ("el-fort-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("any-spec?" ("el-fort-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("all-genl?" ("el-fort-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("any-genl?" ("el-fort-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("spec?" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("genl?" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("union-all-specs" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("all-dependent-specs" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-specs-if" ("function-spec-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-specs" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-not-genls" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-genls-if" ("function-spec-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("union-all-genls" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("all-genls-wrt" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-genls" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("spec-siblings" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("genl-siblings" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("min-not-specs" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("max-specs" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("max-not-genls" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("min-genls" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("union-all-instances" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("not-isa-among" ("hl-term-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("min-not-instances" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("max-instances" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("instance-siblings" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-isas-wrt" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-isa-among" ("hl-term-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("all-instances-among" ("hl-term-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("why-not-isa?" ("hl-term-p" "el-fort-p" "&optional" "hlmt-p" "<tv>" "<behavior>"))
        ("why-isa?" ("hl-term-p" "el-fort-p" "&optional" "hlmt-p" "<tv>" "<behavior>"))
        ("max-floor-mts-of-isa-paths" ("hl-term-p" "el-fort-p" "&optional" "<tv>"))
        ("isa-siblings" ("hl-term-p" "&optional" "hlmt-p" "<tv>"))
        ("instances" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("instances?" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("not-isa?" ("hl-term-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("any-isa-any?" ("listp" "listp" "&optional" "hlmt-p" "<tv>"))
        ("isa-any?" ("hl-term-p" "listp" "&optional" "hlmt-p" "<tv>"))
        ("isa?" ("hl-term-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("map-instances" ("function-spec-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("map-all-instances" ("function-spec-p" "el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("any-wrt-all-isa" ("function-spec-p" "hl-term-p" "&optional" "hlmt-p" "<tv>"))
        ("map-all-isa" ("function-spec-p" "hl-term-p" "&optional" "hlmt-p" "<tv>"))
        ("all-instances" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("all-not-isa" ("hl-term-p" "&optional" "hlmt-p" "<tv>"))
        ("union-all-isa" ("listp" "&optional" "hlmt-p" "<tv>"))
        ("all-isa" ("hl-term-p" "&optional" "hlmt-p" "<tv>"))
        ("max-not-isa" ("hl-term-p" "&optional" "hlmt-p" "<tv>"))
        ("min-isa" ("hl-term-p" "&optional" "hlmt-p" "<tv>"))
        ("diagnose-el-formula" ("listp" "&optional" "hlmt-p" "<io-mode>"))
        ("el-query-ok?" ("listp" "&optional" "hlmt-p"))
        ("el-formula-ok?" ("listp" "&optional" "hlmt-p"))
        ("ground?" ("<expression>" "&optional" "<var?>"))
        ("el-wff-syntax+arity?" ("listp" "&optional" "hlmt-p"))
        ("el-wff-syntax?" ("listp" "&optional" "hlmt-p"))
        ("assertion-el-formula" ("assertion-p"))
        ("el-to-hl-query" ("el-formula-p" "&optional" "hlmt-p"))
        ("el-to-hl" ("el-formula-p" "&optional" "hlmt-p"))
        ("el-strength-p" ("<object>"))
        ("count-all-instances" ("el-fort-p" "&optional" "hlmt-p" "<tv>"))
        ("collections-intersect?" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p"))
        ("collections-disjoint?" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p"))
        ("collections-coextensional?" ("el-fort-p" "el-fort-p" "&optional" "hlmt-p"))
        ("preds-for-pair" ("fort-p" "fort-p" "&optional" "hlmt-p" "<mode>"))
        ("primitive-collection?" ("fort-p" "&optional" "hlmt-p"))
        ("assertions-mentioning-terms" ("<term-list>" "&optional" "<include-meta-assertions?>"))
        ("isa-relevant-assertions" ("hl-term-p" "&optional" "hlmt-p"))
        ("all-term-assertions" ("indexed-term-p" "&optional" "<remove-duplicates?>"))
        ("reviewer" ("fort-p" "&optional" "hlmt-p"))
        ("asserted-when" ("assertion-p"))
        ("asserted-by" ("assertion-p"))
        ("comment" ("fort-p" "&optional" "hlmt-p"))
        ("creation-time" ("fort-p" "&optional" "hlmt-p"))
        ("creator" ("fort-p" "&optional" "hlmt-p"))
        ("result-isa" ("<functor>" "&optional" "hlmt-p"))
        ("arity" ("<relation>" "&optional" "hlmt-p"))
        ("all-sufficient-defns" ("el-fort-p" "&optional" "hlmt-p"))
        ("sufficient-defns" ("el-fort-p" "&optional" "hlmt-p"))
        ("necessary-defns" ("el-fort-p" "&optional" "hlmt-p"))
        ("defining-defns" ("el-fort-p" "&optional" "hlmt-p"))
        ("argn-genl-of" ("el-fort-p" "integerp" "&optional" "hlmt-p"))
        ("min-argn-genl" ("<relation>" "integerp" "&optional" "hlmt-p"))
        ("argn-genl" ("<relation>" "integerp" "&optional" "hlmt-p"))
        ("argn-isa-of" ("el-fort-p" "integerp" "&optional" "hlmt-p"))
        ("min-argn-isa" ("indexed-term-p" "integerp" "&optional" "hlmt-p"))
        ("argn-isa" ("indexed-term-p" "integerp" "&optional" "hlmt-p"))
        ("binary-predicate?" ("fort-p" "&optional" "hlmt-p"))
        ("commutative-function?" ("function-spec-p" "&optional" "hlmt-p"))
        ("commutative-relation?" ("indexed-term-p" "&optional" "hlmt-p"))
        ("relation?" ("indexed-term-p" "&optional" "hlmt-p"))
        ("transitive-predicate?" ("fort-p" "&optional" "hlmt-p"))
        ("anti-symmetric-predicate?" ("fort-p" "&optional" "hlmt-p"))
        ("asymmetric-predicate?" ("fort-p" "&optional" "hlmt-p"))
        ("symmetric-predicate?" ("fort-p" "&optional" "hlmt-p"))
        ("irreflexive-predicate?" ("fort-p" "&optional" "hlmt-p"))
        ("reflexive-predicate?" ("fort-p" "&optional" "hlmt-p"))
        ("pred-value-tuples-in-relevant-mts" ("indexed-term-p" "fort-p" "integerp" "listp" "&optional" "hlmt-p" "truth-p"))
        ("pred-value-tuples-in-any-mt" ("indexed-term-p" "fort-p" "integerp" "listp" "&optional" "truth-p"))
        ("pred-value-tuples-in-mts" ("indexed-term-p" "fort-p" "integerp" "listp" "listp" "&optional" "truth-p"))
        ("pred-value-tuples-in-mt" ("indexed-term-p" "fort-p" "integerp" "listp" "hlmt-p" "&optional" "truth-p"))
        ("pred-value-tuples" ("indexed-term-p" "fort-p" "integerp" "listp" "&optional" "truth-p"))
        ("pred-u-v-holds-in-relevant-mts" ("fort-p" "indexed-term-p" "hl-term-p" "&optional" "hlmt-p" "integerp" "integerp" "truth-p"))
        ("pred-u-v-holds-in-any-mt" ("fort-p" "indexed-term-p" "hl-term-p" "&optional" "integerp" "integerp" "truth-p"))
        ("pred-u-v-holds-in-mts" ("fort-p" "indexed-term-p" "hl-term-p" "listp" "&optional" "integerp" "integerp" "truth-p"))
        ("pred-u-v-holds-in-mt" ("fort-p" "indexed-term-p" "hl-term-p" "hlmt-p" "&optional" "integerp" "integerp" "truth-p"))
        ("pred-u-v-holds" ("fort-p" "indexed-term-p" "hl-term-p" "&optional" "integerp" "integerp" "truth-p"))
        ("some-pred-value-in-relevant-mts" ("indexed-term-p" "fort-p" "&optional" "hlmt-p" "integerp" "truth-p"))
        ("some-pred-value-in-any-mt" ("indexed-term-p" "fort-p" "&optional" "integerp" "truth-p"))
        ("some-pred-value-in-mts" ("indexed-term-p" "fort-p" "listp" "&optional" "integerp" "truth-p"))
        ("some-pred-value-in-mt" ("indexed-term-p" "fort-p" "hlmt-p" "&optional" "integerp" "truth-p"))
        ("some-pred-value" ("indexed-term-p" "fort-p" "&optional" "integerp" "truth-p"))
        ("pred-refs-in-relevant-mts" ("fort-p" "&optional" "hlmt-p" "integerp" "truth-p"))
        ("pred-refs-in-any-mt" ("fort-p" "&optional" "integerp" "truth-p"))
        ("pred-refs-in-mts" ("fort-p" "listp" "&optional" "integerp" "truth-p"))
        ("pred-refs-in-mt" ("fort-p" "hlmt-p" "&optional" "integerp" "truth-p"))
        ("pred-refs" ("fort-p" "&optional" "integerp" "truth-p"))
        ("pred-values-in-relevant-mts" ("indexed-term-p" "fort-p" "&optional" "hlmt-p" "integerp" "integerp" "truth-p"))
        ("pred-values-in-any-mt" ("indexed-term-p" "fort-p" "&optional" "integerp" "integerp" "truth-p"))
        ("pred-values-in-mts" ("indexed-term-p" "fort-p" "listp" "&optional" "integerp" "integerp" "truth-p"))
        ("pred-values-in-mt" ("indexed-term-p" "fort-p" "hlmt-p" "&optional" "integerp" "integerp" "truth-p"))
        ("pred-values" ("indexed-term-p" "fort-p" "&optional" "integerp" "integerp" "truth-p"))
        ("fpred-value-in-relevant-mts" ("indexed-term-p" "fort-p" "&optional" "hlmt-p" "integerp" "integerp" "truth-p"))
        ("fpred-value-in-any-mt" ("indexed-term-p" "fort-p" "&optional" "integerp" "integerp" "truth-p"))
        ("fpred-value-in-mts" ("indexed-term-p" "fort-p" "listp" "&optional" "integerp" "integerp" "truth-p"))
        ("fpred-value-in-mt" ("indexed-term-p" "fort-p" "hlmt-p" "&optional" "integerp" "integerp" "truth-p"))
        ("fpred-value" ("indexed-term-p" "fort-p" "&optional" "integerp" "integerp" "truth-p"))
        ("gather-term-assertions" ("indexed-term-p" "&optional" "hlmt-p"))
        ("gather-predicate-rule-index" ("fort-p" "sense-p" "&optional" "hlmt-p" "<direction>"))
        ("gather-predicate-extent-index" ("fort-p" "&optional" "hlmt-p" "truth-p"))
        ("gather-other-index" ("indexed-term-p"))
        ("gather-nart-arg-index" ("indexed-term-p" "positive-integer-p" "&optional" "<func>"))
        ("gather-mt-index" ("indexed-term-p"))
        ("gather-isa-rule-index" ("el-fort-p" "sense-p" "&optional" "hlmt-p" "<direction>"))
        ("gather-genls-rule-index" ("el-fort-p" "sense-p" "&optional" "hlmt-p" "<direction>"))
        ("gather-genl-mt-rule-index" ("<genl-mt>" "sense-p" "&optional" "<rule-mt>" "<direction>"))
        ("gather-gaf-arg-index" ("indexed-term-p" "positive-integer-p" "&optional" "fort-p" "hlmt-p" "truth-p"))
        ("gather-function-rule-index" ("<func>" "&optional" "hlmt-p" "<direction>"))
        ("gather-function-extent-index" ("<func>"))
        ("gather-exception-rule-index" ("<rule>" "&optional" "hlmt-p" "<direction>"))
        ("gather-index-in-any-mt" ("indexed-term-p" "&optional" "<remove-duplicates?>"))
        ("gather-index" ("indexed-term-p" "&optional" "<remove-duplicates?>"))
        ("map-other-index" ("function-spec-p" "indexed-term-p" "&optional" "truth-p" "<gafs-only>"))
        ("map-mt-index" ("function-spec-p" "hlmt-p" "&optional" "truth-p" "<gafs-only>"))
        ("map-mt-contents" ("function-spec-p" "indexed-term-p" "&optional" "truth-p" "<gafs-only>"))
        ("map-term-gafs" ("function-spec-p" "indexed-term-p" "&optional" "truth-p"))
        ("map-term-selective" ("function-spec-p" "indexed-term-p" "function-spec-p" "&optional" "truth-p"))
        ("map-term" ("function-spec-p" "indexed-term-p"))
        ("relevant-num-predicate-extent-index" ("fort-p"))
        ("relevant-num-nart-arg-index" ("indexed-term-p" "&optional" "positive-integer-p" "<func>"))
        ("relevant-num-gaf-arg-index" ("indexed-term-p" "&optional" "positive-integer-p" "fort-p"))
        ("relevant-num-function-extent-index" ("<func>"))
        ("num-predicate-rule-index" ("fort-p" "&optional" "sense-p" "hlmt-p" "<direction>"))
        ("num-predicate-extent-index" ("fort-p" "&optional" "hlmt-p"))
        ("num-other-index" ("indexed-term-p"))
        ("num-nart-arg-index" ("indexed-term-p" "&optional" "positive-integer-p" "<func>"))
        ("num-mt-index" ("indexed-term-p"))
        ("num-isa-rule-index" ("el-fort-p" "&optional" "sense-p" "hlmt-p" "<direction>"))
        ("num-index" ("indexed-term-p"))
        ("num-genls-rule-index" ("el-fort-p" "&optional" "sense-p" "hlmt-p" "<direction>"))
        ("num-genl-mt-rule-index" ("el-fort-p" "&optional" "sense-p" "hlmt-p" "<direction>"))
        ("num-gaf-arg-index" ("indexed-term-p" "&optional" "positive-integer-p" "fort-p" "hlmt-p"))
        ("num-function-rule-index" ("<func>" "&optional" "hlmt-p" "<direction>"))
        ("num-function-extent-index" ("<func>"))
        ("num-exception-rule-index" ("<rule>" "&optional" "hlmt-p" "<direction>"))
        ("key-predicate-rule-index" ("fort-p" "&optional" "sense-p" "hlmt-p"))
        ("key-predicate-extent-index" ("fort-p"))
        ("key-nart-arg-index" ("indexed-term-p" "&optional" "positive-integer-p" "<func>"))
        ("key-isa-rule-index" ("el-fort-p" "&optional" "sense-p" "hlmt-p"))
        ("key-genls-rule-index" ("el-fort-p" "&optional" "sense-p" "hlmt-p"))
        ("key-genl-mt-rule-index" ("el-fort-p" "&optional" "sense-p" "hlmt-p"))
        ("key-gaf-arg-index" ("indexed-term-p" "&optional" "positive-integer-p" "fort-p"))
        ("key-function-rule-index" ("<func>" "&optional" "hlmt-p"))
        ("key-exception-rule-index" ("<rule>" "&optional" "hlmt-p"))
        ("remove-term-indices" ("indexed-term-p"))
        ("indexed-term-p" ("<object>"))
        ("variable-count" ())
        ("fully-bound-p" ("<object>"))
        ("default-el-var-for-hl-var" ("variable-p"))
        ("variable-id" ("variable-p"))
        ("find-variable-by-id" ("integerp"))
        ("variable-p" ("<object>"))
        ("el-var?" ("<object>"))
        ("make-hl-support" ("hl-module-p" "possibly-sentence-p" "&optional" "fort-p" "tv-p"))
        ("hl-support-p" ("<object>"))
        ("support-sentence" ("support-p"))
        ("support-strength" ("support-p"))
        ("support-truth" ("support-p"))
        ("support-mt" ("support-p"))
        ("support-module" ("support-p"))
        ("support-p" ("<object>"))
        ("deduction-count" ())
	("deduction-assertion" ("deduction-p"))
	("find-deduction-by-id" ("integerp"))
	("deduction-id" ("deduction-p"))
	("deduction-p" ("<object>"))
	("argument-strength" ("argument-p"))
	("argument-truth" ("argument-p"))
	("argument-equal" ("<argument1>" "<argument2>"))
	("asserted-argument-p" ("<object>"))
	("argument-p" ("<object>"))
	("hl-module-p" ("<object>"))
	("hl-term-p" ("<obj>"))
	("atomic-clause-p" ("<clause>"))
	("dnf-formula-from-clauses" ("listp"))
	("dnf-formula" ("<dnf>"))
	("cnf-formula-from-clauses" ("listp"))
	("cnf-formula" ("cnf-p" "&optional" "truth-p"))
	("gaf-cnf?" ("cnf-p"))
	("cnf-p" ("<object>"))
	("ground-clause-p" ("<clause>"))
	("clause-without-literal" ("clause-p" "sense-p" "integerp"))
	("clause-literal" ("clause-p" "sense-p" "integerp"))
	("empty-clause?" ("clause-p"))
	("empty-clause" ())
	("clause-equal" ("<clause1>" "<clause2>"))
	("pos-lits" ("clause-p"))
	("neg-lits" ("clause-p"))
	("make-clause" ("listp" "listp"))
	("sense-p" ("<object>"))
	("clause-p" ("<object>"))
	("negate" ("el-formula-p"))
	("negated?" ("el-formula-p"))
	("assertion-count" ())
	("assertion-has-dependents-p" ("assertion-p"))
	("assertion-el-ist-formula" ("assertion-p"))
	("deduced-assertion?" ("assertion-p"))
	("asserted-assertion?" ("assertion-p"))
	("get-asserted-argument" ("assertion-p"))
	("find-all-gafs" ("el-formula-p"))
	("find-gaf-any-mt" ("el-formula-p"))
	("find-gaf" ("el-formula-p" "fort-p"))
	("find-all-assertions" ("cnf-p"))
	("find-assertion-any-mt" ("cnf-p"))
	("find-assertion" ("cnf-p" "fort-p"))
	("find-assertion-by-id" ("integerp"))
	("assertion-has-meta-assertions?" ("assertion-p"))
	("assertion-strength" ("assertion-p"))
	("truth-p" ("<object>"))
	("assertion-has-truth" ("assertion-p" "truth-p"))
	("assertion-truth" ("assertion-p"))
	("code-assertion?" ("assertion-p"))
	("direction-p" ("<object>"))
	("backward-assertion?" ("assertion-p"))
	("forward-assertion?" ("assertion-p"))
	("assertion-direction" ("assertion-p"))
	("assertion-mt" ("assertion-p"))
	("assertion-mentions-term" ("assertion-p" "hl-term-p"))
	("assertion-ist-formula" ("assertion-p"))
	("assertion-formula" ("assertion-p"))
	("assertion-cnf" ("assertion-p"))
	("assertion-id" ("assertion-p"))
	("assertion-p" ("<object>"))
	("fort-count" ())
	("remove-fort" ("fort-p"))
	("fort-el-formula" ("fort-p"))
	("el-fort-p" ("<object>"))
	("fort-p" ("<object>"))
	("nart-count" ())
	("remove-nart" ("nart-p"))
	("nart-el-formula" ("nart-p"))
	("nart-hl-formula" ("nart-p"))
	("find-nart-by-id" ("integerp"))
	("nart-id" ("nart-p"))
	("nart-p" ("<object>"))
	("constant-apropos" ("stringp" "&optional" "booleanp" "fixnump" "<end>"))
	("constant-complete" ("stringp" "&optional" "booleanp" "booleanp" "fixnump" "<end>"))
	("constant-complete-exact" ("stringp" "&optional" "fixnump" "<end>"))
	("valid-constant-name" ("stringp"))
	("valid-constant-name-char" ("characterp"))
	("constant-count" ())
	("remove-constant" ("constant-p"))
	("uniquify-constant-name" ("stringp"))
	("rename-constant" ("constant-p" "stringp"))
	("find-or-create-constant" ("stringp" "&optional" "constant-external-id-p"))
	("create-constant" ("stringp" "&optional" "constant-external-id-p"))
	("find-constant-by-internal-id" ("constant-internal-id-p"))
	("find-constant-by-external-id" ("constant-external-id-p"))
	("find-constant" ("stringp"))
	("constant-name" ("constant-p"))
	("constant-internal-id" ("constant-p"))
	("constant-external-id" ("constant-p"))
	("constant-p" ("<object>"))
	))

(provide 'cyc-api-data)
